blank_issues_enabled: false  # default: true
contact_links:
- name: 📝 Ansible Community Code of Conduct
  url: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_template_chooser
  about: ❤ Be nice to other members of the community. ☮ Behave.
- name: 📑 Ansible Content Collection Inclusion
  url: https://github.com/ansible-collections/overview/blob/main/collection_checklist.md
  about: Process to include a new collection into the Ansible package.
- name: 💬 Talks to the community
  url: https://docs.ansible.com/ansible/latest/community/communication.html?utm_medium=github&utm_source=issue_template_chooser#mailing-list-information
  about: Please ask and answer usage questions here.
- name: ⚡ Working groups
  url: https://github.com/ansible/community/wiki
  about: Interested in improving a specific area? Become a part of a working group!
